import os
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()

api_key = os.getenv("OPENAI_API_KEY")
client = OpenAI(api_key=api_key) if api_key else None


def generate_advisory(condition: str, patient_data: dict, risk_score: float,
                       risk_level: str, shap_values: dict) -> str:

    # Get top 3 most impactful features
    top_factors = list(shap_values.items())[:3]
    factors_text = "\n".join([
        f"- {feat}: SHAP impact = {val:+.4f} "
        f"({'increases' if val > 0 else 'reduces'} risk)"
        for feat, val in top_factors
    ])

    condition_name = "heart disease" if condition == "heart" else "diabetes"

    prompt = f"""You are a clinical decision support assistant. Based on the following 
patient data and machine learning analysis, write a clear, professional, 
plain-English clinical advisory note.

Condition being assessed: {condition_name}
Risk Score: {risk_score}%
Risk Level: {risk_level}
Patient Data: {patient_data}

Top 3 contributing factors from explainable AI analysis:
{factors_text}

Write a structured advisory note with these three sections:
1. Patient Risk Summary (1-2 sentences)
2. Key Risk Factors (explain the top factors in plain English)
3. Recommendation (what action is advised)

Important: Always end with this disclaimer:
"This output is generated by an AI decision-support tool and must not be used 
as a substitute for professional clinical diagnosis or medical advice."

Keep the tone professional but accessible. Maximum 150 words."""

    try:
        response = client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[{"role": "user", "content": prompt}],
            max_tokens=300,
            temperature=0.7,
        )
        return response.choices[0].message.content

    except Exception as e:
        # Fallback if API unavailable
        return generate_fallback_advisory(
            condition_name, risk_score, risk_level, top_factors
        )


def generate_fallback_advisory(condition_name: str, risk_score: float,
                                risk_level: str, top_factors: list) -> str:
    factor_lines = []
    for feat, val in top_factors:
        direction = "increases" if val > 0 else "reduces"
        factor_lines.append(f"{feat} ({direction} risk)")

    factors_str = ", ".join(factor_lines)

    return (
        f"Patient Risk Summary: This patient has been assessed as {risk_level.upper()} "
        f"risk for {condition_name} with a risk score of {risk_score}%.\n\n"
        f"Key Risk Factors: The primary contributing factors identified by the "
        f"AI analysis are: {factors_str}.\n\n"
        f"Recommendation: {'Prompt clinical review is advised given the elevated '  + 'risk profile identified.' if risk_level == 'High' else 'Continued monitoring and preventative measures are recommended.' if risk_level == 'Medium' else 'Continue current health management and routine monitoring.'}\n\n"
        f"This output is generated by an AI decision-support tool and must not "
        f"be used as a substitute for professional clinical diagnosis or medical advice."
    )


if __name__ == "__main__":
    # Test with fallback (no API key needed for this test)
    print("Testing advisory generation...")

    test_shap = {
        "cp": -0.71,
        "trestbps": -0.54,
        "chol": -0.38,
        "age": -0.29,
        "thalach": 0.24
    }

    test_patient = {
        "age": 54, "sex": 1, "cp": 3, "trestbps": 145,
        "chol": 233, "fbs": 1, "restecg": 0, "thalach": 150,
        "exang": 0, "oldpeak": 2.3, "slope": 0, "ca": 0, "thal": 1
    }

    result = generate_fallback_advisory(
        "heart disease", 78.5, "High", list(test_shap.items())[:3]
    )
    print(result)
    print("\n✅ Advisory module working.")
    